### ISSUE TITLE
topN ?

### ISSUE THREAD

**Issue by dcsan** [peterolson/chinese-lexicon#1]
one function nodejieba has is "topN" words by rarity.
would be nice if you had that function then i could ditch jieba...

**Comment by peterolson** [comment]
I'm not quite sure I understand what you mean?

**Comment by dcsan** [comment]
I am currently using the nodejieba method 

```
let words = nodejieba.extract(text, topN) // find top rare words
```

for other stuff i'm mostly using your libraries now (or my fork of them)
if you were to add the `.extract` method to your lib I could drop jieba.
having this many separate native C libraries (that probably use same underlying code) is a bit heavy on the system, I can feel it glitch when the libraries/dictionaries are loaded at startup.

**Comment by peterolson** [comment]
This library doesn't do word segmentation, so I'm not sure how this library could do this without relying on jieba. Once the words are segmented you can sort them by their movie/book frequency.
